atlcore/site/forms.py
from django import forms
from captcha.fields import CaptchaField
from django.utils.translation import ugettext_lazy as _

class ContactFormWithCaptcha(forms.Form):
    
    name = forms.CharField(label=_("Name"), max_length=50)
    email = forms.CharField(label=_("Email address"), required=False)
    country = forms.CharField(label=_("Country"), max_length=50, required=False)
    message = forms.CharField(label=_('Comment'), widget=forms.Textarea, max_length=200)
    
    captcha = CaptchaField(error_messages = {   'required': 'Este campo es requerido.',     'invalid': 'Captcha incorrecto.', })
    
class UserSubscriber(forms.Form):
    email = forms.EmailField()

atlcore/site/views.py
# -*- coding: utf-8 -*-
from django.template.context import RequestContext
from django.http import HttpResponse
from django.shortcuts import render_to_response
from atlcore.contenttype.models import Folder, Node


def details_view(request, id=None, slug=None, view_name=None):
    context = {}
    context['atl_node'] = Node.objects.get(id=id).get_instance()
    return render_to_response('mysite/news.html',
                              context,
                              context_instance=RequestContext(request))

atlcore/site/templates/site/ajax_message.html
{{message}}

atlcore/site/templates/site/aspect.html
{% extends "site/main.html" %}
{% load i18n %}

{% block styles %}
    {{block.super}}
	<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}skins/{{skin.slug}}/css/aspect.css" />
{% endblock %}

{% block main %}
<ul>
    {% for content in contents %}
	<li>
		<h2><a href="{{content.get_absolute_url}}">{{content.title}}</a></h2>
			{{content.description|safe}}
	</li>
	{% endfor %}	
</ul>
{% endblock %}

atlcore/site/templates/site/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}">
	<head>
		
	{% load i18n admin_static%}
	    <title>{% block title %}{{ dc.title }}{% endblock %}</title>
	    <meta name="Description" content='{{dc.description|striptags|truncatewords:150}}' />
	    <meta name="Keywords" content="{{dc.keywords}}" />
		<meta http-equiv=Content-Type content="text/html; charset=UTF-8">
		<meta name="Author" content="{{dc.author}}" />
		<meta name="Copyright" content="{{dc.copyright}}" />
		<meta name="Creator" content="{{dc.creator}}" />
		<meta name="Distribution" content="Global" />
		<meta name="Rating" content="General" />

		
<!-- begin styles block -->
	{% block styles %}
	    <link rel="stylesheet" type="text/css" href="{% static "site/css/base.css" %}" />
	    <!-- Grid 960 styles-->
	    <link rel="stylesheet" type="text/css" media="all" href="{% static "grid-960/css/reset.css"%}" />
  		<link rel="stylesheet" type="text/css" media="all" href="{% static "grid-960/css/text.css"%}" />
  		<link rel="stylesheet" type="text/css" media="all" href="{% static "grid-960/css/960.css"%}" />
		<link rel="stylesheet" type="text/css" href="{% static "skins/" %}{{skin.slug}}/css/base.css" />
		<!-- Components styles environment -->
		{% for css in media_environment.styles %}
			<link id="{{css.keys|first}}" href="{% static css.values|first %}" type="text/css" rel="stylesheet"> </link>
		{% endfor %}
		<!-- End Components styles environment -->

	{% endblock %}
<!-- end styles block -->	
	
<!-- begin scripts block -->	
	
	{% block scripts %}
		<script id="lib_atlcore" type="text/javascript" src="{% static "common/js/atlcore.js" %}"></script>
		<!-- Components scripts environment -->
		{% for script in media_environment.scripts %}
			<script id="{{script.keys|first}}" src="{% static script.values|first %}" type="text/javascript"></script>
		{% endfor %}
		<!-- end Components scripts environment -->


	{% endblock %}
<!-- end scripts block -->	

	{% block extrahead %}
	{% endblock %}
<!-- begin google_analytics_code -->	
	{% if site_profile.google_analytics_script %}
		{{site_profile.google_analytics_script|safe}}
	{% endif %}
<!-- end google_analytics_code -->
	</head>

	<body class="{% block bodyclass %}{% endblock %}">
		{% block content %}
		{% endblock %}
	</body>
</html>

atlcore/site/templates/site/contact.html
{% extends templateParent|default:"site/main.html" %}

{% block styles %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{{ATL_MEDIA_URL}}site/css/contact.css" />
{% endblock %}



{% block main %}

	<form id = "formContact" action="/contact/"  method="post">{% csrf_token %}
		<p>
			Le responderemos en la mayor brevedad posible.<br/> Estamos a su disposición.
		</p>
		
		<div class="formLeft">
			
			<input id="next" name="next" type="hidden" class="next" value='{{url_short}}'/>
			
			{{form.name}}
			
		    {{form.email}}
		    
		</div>
	    
	    
	    <div class="formRight">
	    	
	    	{{form.message}}
	    
	        {% if form.captcha.errors %}{{ form.captcha.errors }}{% endif %}
	        
	        <div class="captcha">{{form.captcha }}</div>
	        
	        <input class="submit  {{LANGUAGE_CODE}}" type="submit"  value="ENVIAR"/>
	        
	    </div>
	    
	    <p class="error">
	    	<br/>
			{{message}}
	    </p>
	</form>
	
	
	<script type="text/javascript">
	$(function(){
		
		$('form input[type="text"]').each(function() {
			if($(this).attr("value") == ""){
				if($(this).attr("name") == "name"){ 
					$(this).attr("value","NOMBRE");
				}
			
				if($(this).attr("name") == "email"){
					$(this).attr("value","EMAIL");
				}
				
				if($(this).attr("name") == "captcha_1"){
					$(this).attr("value","CAPTCHA");
				}
			}
		});
		
		
		$('form textarea').each(function() {
		  	if($(this).attr("value") == ""){
		  		if($(this).attr("name") == "message"){
		  			$(this).attr("value","MENSAJE");
		  		}
			}
		});
		
	
		$('form input[type="text"]').focus(function() {
			if($(this).attr("value") == "NOMBRE"){
				$(this).attr("value","");
			}
			
			if($(this).attr("value") == "EMAIL"){
				$(this).attr("value","");
			}
		});
		
		
		$('form textarea').focus(function() {		
			if($(this).attr("value") == "MENSAJE"){
				$(this).attr("value","");
			}
		});
		
		
		$('form input[type="text"]').blur(function() {
			if($(this).attr("value") == ""){
				if($(this).attr("name") == "name"){ 
					$(this).attr("value","NOMBRE");
				}
			
				if($(this).attr("name") == "email"){
					$(this).attr("value","EMAIL");
				}
			}
		});
		
		$('form textarea').blur(function() {
		  	if($(this).attr("value") == ""){
		  		if($(this).attr("name") == "message"){
		  			$(this).attr("value","MENSAJE");
		  		}
			}
		});
		
		var default_value_captcha = "CAPTCHA";
		
		$('form #id_captcha_1').focus(function() {
			if($(this).attr("value") == default_value_captcha){
				$(this).attr("value","");
			}
		});
		
		$('form #id_captcha_1').blur(function() {
		  if($(this).attr("value") == ""){
		  		$(this).attr("value",default_value_captcha);
			}
		});
	
	$("form#formContact").submit(function(event){
			var name = $("form#formContact input#id_name").val();
			
			var emailp = $("form#formContact input#id_email").val();
			
			var commentsp = $("form#formContact textarea").val();
			
			var captcha_0 = $("form#formContact #id_captcha_0").val();
			
			var captcha_1 = $("form#formContact #id_captcha_1").val();
			
			if (captcha_1 =="" || captcha_1 =="captcha" ){
				alert("Debe entrar un captcha válido.");
				return false;
			} else if (emailp =="" || emailp =="EMAIL" || commentsp == "" || commentsp == "MENSAJE" || name == "" || name == "NOMBRE"){
				alert("Debe entrar su nombre, correo electrónico y el mensaje a enviar.");
				return false;
			}
			return true;
	
	});
	
	
	}); 
	</script>
	
	




{% endblock main %}

atlcore/site/templates/site/container.html
{% extends templateParent|default:"site/main.html" %}

{% block styles %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{{ATL_MEDIA_URL}}site/css/{{content.content_type.name}}.css" />
	<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}skins/{{skin.slug}}/css/container.css" />
	<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}skins/{{skin.slug}}/css/{{content.content_type.name}}.css" />
{% endblock %}

{% load i18n %}


{% block main %}
	{% block before_main %}
	{% endblock %}
		{% load vcl%}
		{% show_component content_component component_view %}
	{% block after_main %}
	{% endblock %}
{% endblock %}

atlcore/site/templates/site/content.html
{% extends templateParent|default:"site/main.html" %}

{% load admin_static %}

{% block styles %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{%static ""%}site/css/{{content.content_type.name}}.css" />
	<link rel="stylesheet" type="text/css" href="{%static ""%}skins/{{skin.slug}}/css/{{content.content_type.name|lower}}.css" />
{% endblock %}

{% load i18n %}


{% block main %}
	{% block before_main %}
	{% endblock %}
		{% load vcl%}
		{% show_component content_component template_name %}
	{% block after_main %}
	{% endblock %}
{% endblock %}

atlcore/site/templates/site/email_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<head>
	{% block styles %}
	<style>
		body {
			width: 703px;
			margin:0 auto;
			padding:0px;
		}
	</style>
	{% endblock %}
	</head>
	<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
	{% block content %}
	{% endblock %}
	</body>
</html>

atlcore/site/templates/site/errors_main.html
{% extends templateParent|default:"site/base.html" %}
{% load i18n %}

{% block styles %}
{{block.super}}
<link type="text/css" href="{{ATLANTE_CMS_MEDIA_URL}}site/styles/error.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div id="container">
	<div id="header">
		{% block head %}
		<div id="logo">
			<a href="/"><img title="AtlanteCMS Site" atl="AtlanteCMS Site" src="/atlante_cms_media/admin/images/logo.png"/></a>
		</div>
		{% endblock%}
	</div> 
	<div id="center_area">
	{% block full %}{% endblock%}
	</div>
	<div id="footer">
		{% block footer %}
		<a class="atl_site" href="http://www.atlantesoftware.com">AtlanteSoftware 2010</a>
		{% endblock%}
	</div>
</div>
{% endblock %}

atlcore/site/templates/site/main.html
{% extends templateParent|default:"site/base.html" %}
{% load i18n admin_static%}

{% block styles %}
{{block.super}}

{% endblock %}

{% block content %}
<div class="container_12">
	<div id="site_header" class="grid_12">
		<a href="/"><img title="AtlanteCMS Site" atl="AtlanteCMS Site" src="{% static "atlcms/images/logo.png" %}" /></a>
	</div>
	<div class="clear"></div>
	<div class="grid_3">
		{% block left_column %}
			<ul>
			    {% for f in navigation_container %}
			    <li><a href='{{f.get_absolute_url}}'>{{f.title}}</a></li>
			    {% endfor %}
			</ul>
			{% endblock %}
	</div>
	<div class="grid_6">
		    <div id="main">
		        {% block main %}
		                En este bloque saldrá el contenido principal de la página
		        {% endblock %}
		    </div>

		
	</div>
	<div class="grid_3">
		{% block right_column %}
		{% endblock %}
	</div>
	<div class="clear"></div>
	<div id="footer" class="grid_12">
		<a class="atl_site" href="http://www.atlantesoftware.com">AtlanteSoftware 2010</a>
	</div>
	<div class="clear"></div>
	<div class="grid_7 topSection">
		
		<div> xxx</div>
	</div>
	<div class="grid_5 topSection">
		yyy
	</div>
</div>
<!-- END Container -->

{% endblock %}

atlcore/site/templates/site/message.html
{{message}}

atlcore/site/templates/site/search.html
{% extends templateParent|default:"site/searchParent.html" %}

atlcore/site/templates/site/searchParent.html
{% extends templateParent|default:"site/main.html" %}

{% block styles %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{{ATL_MEDIA_URL}}vcl/css/search.css" />
	<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}skins/{{skin.slug}}/css/container.css" />
{% endblock %}

{% load i18n %}


{% block main %}
	{% block before_main %}
	{% endblock %}
	
	{% load vcl %}
	
	{% load siteutils %}
	
	<div id="content">
		<div id="search" class="container_list">
			
			
			<h1>{{component.title}}</h1>
			{% if component.page.object_list|length > 0 %}
			
			<p class="results">
				Se han encontrado {{component.page.paginator.count}} resultado(s)
			</p>
			
				<ul class="children">
				{% for item in component.page.object_list %}
				<li class="{% if forloop.first %}first{%endif%}{%if forloop.last%}last{%endif%}">
					<div>
						
							<a href="{{item.object.get_absolute_url}}">
								<img src="{% get_image_crop_url item.object 160 105 %}"/>
							</a>
						
						<h2><a href="{{item.object.get_absolute_url}}">{{item.object.title}}</a></h2>
						
						{% if item.object.get_instance.body %}
							<p>{{item.object.body|safe|striptags|truncatewords:"25"}}</p>
						{% else %}
							<p>{{item.object.description|safe|striptags|truncatewords:"25"}}</p>
						{% endif %}
				
						<div class="clearfix"></div>
				
					</div>
				</li>
				{% endfor %}
			{% else %}
			
			<p class="results">
				No se encontraron resultados para la búsqueda que realizó
			</p>
				{% endif %}
				</ul>
				
		{% if component.page.object_list|length > 0 %}
			<div class="pagination">
			    <div class="step-links">
			        {% if component.page.has_previous %}
				        <div class="button_left">
				            <a href="?page={{ component.page.previous_page_number }}"><img src="{{ATL_MEDIA_URL}}vcl/images/paginator_left_button.jpg" alt="anterior"/></a>
				        </div>
			        {% else %}
				        <div class="button_left">
				            <img src="{{ATL_MEDIA_URL}}vcl/images/paginator_left_button.jpg" alt="anterior"/>
				        </div>
			        {% endif %}
			        
			        
			        {% if component %}
			        <div class="pages_list">
			        	{% get_paginator_near_page_list component.page.number component.page.paginator.num_pages 7 %}
			        </div>
			 		{% endif %}
			 		
			 		
			        {% if component.page.has_next %}
				        <div class="button_right">
				            <a href="?page={{ component.data_provider.paginated_childrens.next_page_number }}"><img src="{{ATL_MEDIA_URL}}vcl/images/paginator_right_button.jpg" alt="próximo"/></a>
				        </div>
				    {% else %}
				    	<div class="button_right">
				            <img src="{{ATL_MEDIA_URL}}vcl/images/paginator_right_button.jpg" alt="próximo"/>
				        </div>   
			        {% endif %}
			    </div>
			</div>
		{% endif %}
		
		<h2 class="errors">
			{{errors}}
		</h2>
			
		</div>

	</div>
		
	{% block after_main %}
	{% endblock %}
{% endblock %}

atlcore/site/templates/site/user_message.html
{% extends templateParent|default:"site/main.html" %}

{% block main %}
	<div class="message">
	{{message}}
	</div>
{% endblock %}

atlcore/site/templates/site/utils/get_image_crop.html
{{image_absolute_url}}

atlcore/site/templates/site/utils/get_image_crop_url.html
{{image_url}}

atlcore/site/templates/site/utils/get_paginator_near_page_list.html
{% for num in page_nums %}
<a href="?page={{num}}{% if search != 'None' %}&q={{search}}{% endif %}" class="{% if num == current_page %}selected{% endif %} {% if forloop.last %}last{% endif %}">{{num}}</a>
{% endfor%}

atlcore/site/templates/vcl/content/container_details.html
{% if component.data_provider|length > 0 %}
<ul class="children">
{% for child in component.data_provider %}
<li>
	<div>
		<a href="{{child.get_absolute_url}}">
			<img src="{{child.get_image_thumbnail}}"/>
		</a>
	</div>
</li>
{% endfor %}
{% endif %}
</ul>

atlcore/site/templates/vcl/content/container_gallery.html
<div class="container_gallery">
	{% if component.data_provider.getChildren|length > 0 %}
		<ul class="children">
		{% for child in component.data_provider.getChildren %}
		<li><div>
			<a href="{{child.get_absolute_url}}">
				<img src="{{child.get_image_thumbnail}}"/>
			</a></div>
		</li>
		{% endfor %}
		{% endif %}
		</ul>
</div>

atlcore/site/templates/vcl/content/container_list.html
<div id="{{component.id}}" class="container_list">
	<h1>{{component.data_provider.title}}</h1>
	{% if component.data_provider.getChildren|length > 0 %}
		<ul class="children">
		{% for child in paginator.object_list %}
		<li class="{% if forloop.first %}first{%endif%}{%if forloop.last%}last{%endif%}">
			<div>
				<a href="{{child.get_absolute_url}}">
					<img src="{{child.get_image_thumbnail}}"/>
				</a>
				<h2><a href="{{child.get_absolute_url}}">{{child.title}}</a></h2>
				{{child.description|safe|truncatewords:33}}
			</div>
		</li>
		{% endfor %}
		{% endif %}
		</ul>
	<div class="pagination">
	    <div class="step-links">
	        {% if component.data_provider.paginated_childrens.has_previous %}
		        <div class="button_left">
		            <a href="?page={{ component.data_provider.paginated_childrens.previous_page_number }}"><img src="/files/skins/basesite/images/paginator_left_button.jpg" alt="anterior"/></a>
		        </div>
	        {% else %}
		        <div class="button_left">
		            <img src="/files/skins/basesite/images/paginator_left_button.jpg" alt="anterior"/>
		        </div>
	        {% endif %}
	        <div class="pages_list">
	        	{% get_paginator_near_page_list component.data_provider.paginated_childrens.number component.data_provider.paginated_childrens.paginator.num_pages 7 %}
	        </div>
	 
	        {% if component.data_provider.paginated_childrens.has_next %}
		        <div class="button_right">
		            <a href="?page={{ component.data_provider.paginated_childrens.next_page_number }}"><img src="/files/skins/basesite/images/paginator_right_button.jpg" alt="próximo"/></a>
		        </div>
		    {% else %}
		    	<div class="button_right">
		            <img src="/files/skins/basesite/images/paginator_right_button.jpg" alt="próximo"/>
		        </div>   
	        {% endif %}
	    </div>
	</div>		
</div>

atlcore/site/templates/vcl/content/container_thumbnails.html
	<div class="container_thumbnails">
		{% if component.data_provider.getChildren|length > 0 %}
		<ul class="children">
		{% for child in component.data_provider.getChildren %}
		<li><div>
			<a href="{{child.get_absolute_url}}">
				<img src="{{child.get_image_thumbnail}}"/>
			</a></div>
		</li>
		{% endfor %}
		{% endif %}
		</ul>
	
	</div>

atlcore/site/templates/vcl/content/content_ajax.html
{% load vcl%}
{% show_component content_component component_view %}

atlcore/site/templates/vcl/content/content_details.html
	<div id="content_details">
		{% if component.data_provider.creator %}
			<div class="field_creator">{{component.data_provider.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.data_provider.title}}</h1>
		{% if component.data_provider.date %}
			<div class="field_date">{{component.data_provider.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.data_provider.source %}
			<div class="field_source">{{component.data_provider.source}}</div>
		{% endif %}
		{% if component.data_provider.contributor %}
			<div class="field_contributor">{{component.data_provider.contributor}}</div>
		{% endif %}
		{% if component.data_provider.description %}
			<div class="field_description">{{component.data_provider.description|safe}}</div>
		{% endif %}
		{% if component.data_provider.body %}
			<div class="field_body">{{component.data_provider.body|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/document_preview.html
	<div class="preview">
		{% if component.source.creator %}
			<div class="field_creator">{{component.source.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.source.title}}</h1>
		{% if component.source.date %}
			<div class="field_date">{{component.source.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.source.source %}
			<div class="field_source">{{component.source.source}}</div>
		{% endif %}
		{% if component.source.contributor %}
			<div class="field_contributor">{{component.source.contributor}}</div>
		{% endif %}
		{% if component.source.description %}
			<div class="field_description">{{component.source.description|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/folder_details.html
	<div id="details">
		
		{% include 'vcl/content/include/details.html' %}
		
		{% if component.data_provider.body %}
			<div class="field_body">{{component.data_provider.body|safe}}</div>
		{% endif %}
		
		{% if component.data_provider.getChildren|length > 0 %}
		<ul class="children">
		{% for child in component.data_provider.getChildren %}
		<li>
			<a href="{{child.get_absolute_url}}" {% if child.instance_class_name == 'file' %} target="{{child.id}}" {%endif%}>
				{{child.title}}
			</a>
		</li>
		{% endfor %}
		{% endif %}
		</ul>
	</div>

atlcore/site/templates/vcl/content/folder_preview.html
	<div class="preview">
		{% if component.source.creator %}
			<div class="field_creator">{{component.source.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.source.title}}</h1>
		{% if component.source.date %}
			<div class="field_date">{{component.source.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.source.source %}
			<div class="field_source">{{component.source.source}}</div>
		{% endif %}
		{% if component.source.contributor %}
			<div class="field_contributor">{{component.source.contributor}}</div>
		{% endif %}
		{% if component.source.description %}
			<div class="field_description">{{component.source.description|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/news_details.html
	<div id="news_details">
		{% include 'vcl/content/include/details.html' %}
		{% if component.data_provider.body %}
			<div class="field_body">{{component.data_provider.body|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/news_preview.html
	<div class="news_preview">
		{% if component.data_provider.image %}
			<img class="field_image" src="{{component.data_provider.image.url}}" alt="image" />
		{% endif %}

		{% if component.data_provider.creator %}
			<div class="field_creator">{{component.data_provider.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.data_provider.title}}</h1>
		{% if component.data_provider.date %}
			<div class="field_date">{{component.data_provider.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.data_provider.description %}
			<div class="field_description">{{component.data_provider.description|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/picture_preview.html
	<div class="preview">
		{% if component.source.creator %}
			<div class="field_creator">{{component.source.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.source.title}}</h1>
		{% if component.source.date %}
			<div class="field_date">{{component.source.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.source.source %}
			<div class="field_source">{{component.source.source}}</div>
		{% endif %}
		{% if component.source.contributor %}
			<div class="field_contributor">{{component.source.contributor}}</div>
		{% endif %}
		{% if component.source.description %}
			<div class="field_description">{{component.source.description|safe}}</div>
		{% endif %}
	</div>

atlcore/site/templates/vcl/content/video_details.html
<div id="details">
	{% load vcl %}
	{% show_component component.video_player %}
	<h1>{{component.data_provider.title}}</h1>
	{% if component.source.body %}
		<div class="field_body">{{component.source.body|safe}}</div>
	{% endif %}
</div>

atlcore/site/templates/vcl/content/video_preview.html
	<div class="preview">
		{% if component.source.creator %}
			<div class="field_creator">{{component.source.creator}}</div>
		{% endif %}
		<h1 class="field_title">{{component.source.title}}</h1>
		{% if component.source.date %}
			<div class="field_date">{{component.source.date|date:"d.m.Y"}}</div>
		{% endif %}
		{% if component.source.source %}
			<div class="field_source">{{component.source.source}}</div>
		{% endif %}
		{% if component.source.contributor %}
			<div class="field_contributor">{{component.source.contributor}}</div>
		{% endif %}
		{% if component.source.description %}
			<div class="field_description">{{component.source.description|safe}}</div>
		{% endif %}
	</div>